### ISSUE TITLE
Loyal

### ISSUE THREAD

**Issue by loyalcom** [james2doyle/clean-css-chrome-app#2]
@charset "utf-8";
body { margin:0; padding:0; width:100%; background:#f0f0f0;}
html { padding:0; margin:0;}
a { text-decoration:none;}
a:hover { text-decoration:underline;}
/\* main _/
.main { padding:0; margin:0 auto;}
/_********\* header *********_/
.blok_header { margin:0; padding:0; background: #f0f0f0 url(images/header_bg3.gif) top center repeat-x;}
.header { width:960px; margin:0 auto; padding:0;}
.header h2 { font:normal 48px Arial, Helvetica, sans-serif; color:#454545; padding:20px 0 35px 15px; margin:0;}
/_ logo _/
.logo { padding:0; margin:0; float:left; width:287px;}
/_ menu _/  
.menu { padding:10px 0; margin:0; float:left;}
.menu ul { text-align: left; padding:0; margin:0; list-style:none; border:0; float:left;}
.menu ul li { float:left; margin:0; padding:0 5px 0 0; border:0;}
.menu ul li a { float:left; margin:0; padding:10px; color:#363636; font:bold 12px Arial, Helvetica, sans-serif; text-decoration:none;}
.menu ul li a:hover { color:#fff; background:#454545;}
.menu ul li a.active { color:#fff; background:#454545;}
/_ livesupport _/
.livesupport { padding:0; margin:0; width:320px; float:right;}
/_ Ca3er style */
.cu3er_resize { width:960px; margin: auto; padding:0 0 37px 0; background: url(images/simple_bg.gif) no-repeat bottom;}
# cu3er-container { width:960px; outline:0;}

/*********\* body *********_/
.body_resize { margin:0; padding:0; background:#f0f0f0;}
.body { width:960px; margin:0 auto; padding:10px 0;}
.body h2 { font: normal 24px Arial, Helvetica, sans-serif; color:#454545; margin:0; padding:15px 0;}
.body img { padding:0; margin:10px auto;}
.body img.floated { float:left; padding:0; margin:10px 15px 10px 0;}
.body p { font:normal 12px Arial, Helvetica, sans-serif; color:#838383; line-height:1.5em; padding:5px 0; margin:0;}
.body p span { font: bold 12px Arial, Helvetica, sans-serif; color:#277fc2;}
.body a { text-decoration:underline; color:#008ac3;}
.right { width:290px; float:right; padding:15px; margin:0;}
.left { width:610px; float:left; padding:15px; margin:0;}
.full { padding:5px 15px; margin:0;}
.block { width:231px; float:left; margin:10px 5px 10px 1px; padding:10px 0;}
.port_resize { width:290px; float:left; margin:0; padding:15px;}
.port_resize2 { width:960px; float:left; margin:0; padding:0;}
.port_resize3 { width:930px; float:left; margin:0; padding:15px;}
.body ul { list-style:none; margin:10px; padding:0;}
.body li { background:url(images/ul_li.gif) left no-repeat; font: bold 12px Arial, Helvetica, sans-serif; color:#008ac3; padding:3px 0 3px 15px;}
/_FBG_/
.FBG { background:#f0f0f0; margin:0; padding:0;}
.FBG_resize { width:960px; margin:0 auto; padding:15px 0; border-top:1px solid #c9c9c9;}
.FBG_resize p { font: normal 11px Arial, Helvetica, sans-serif; color:#444; padding:5px 0; margin:0; line-height:1.5em;}
.FBG_resize img { float:left; margin:5px; padding:0;}
.FBG_resize h2 { font: bold 14px Arial, Helvetica, sans-serif; color:#454545; padding:5px 0; margin:0;}
.FBG_resize .lefta { border-right:1px solid #d8d8d8; width:209px; float:left; margin:0; padding:15px;}
.FBG_resize .lefta.last { border:0;}
/_ END_bloga*/
/************_footer**_******_/
.footer { padding:0; margin:0; background:#f0f0f0;}
.footer_resize { width:940px; margin:0 auto; padding:20px 10px; border-top:1px solid #c9c9c9;}
.footer p { font:normal 11px Arial, Helvetica, sans-serif; color:#3e3d3d;}
.footer a { font:normal 11px Arial, Helvetica, sans-serif; color:#008ac3; text-decoration:none; padding:5px; margin:0;}
.footer p.right { text-align:right; width:350px; margin:0; padding:15px 0 0 0; float:right;}
.footer p.leftt { text-align:left; width:550px; margin:0; padding:15px 0 0 0; float:left;}
/**_******\* contact form *********_/
.form { float:left; width:550px; margin:5px auto; padding:0; background:#fff; border:1px solid #dedede;}
/**_******\* contact form **********/
# contactform { margin:0; padding:5px 0;}
# contactform \* { color:#7a7a7a;}
# contactform ol { margin:0; padding:0; list-style:none;}
# contactform li { margin:0; padding:0; background:none; border:none; display:block;}
# contactform li.buttons { margin:5px 0 5px 0;}
# contactform label { float:left; margin:0; width:150px; padding:5px 0; font:normal 12px Arial, Helvetica, sans-serif; color:#838383; text-transform:capitalize;}
# contactform label span { font:normal 10px Arial, Helvetica, sans-serif;}
# contactform input.text { width:480px; border:1px solid #e9e9e9; margin:5px 0; padding:5px 2px; height:15px; background:#f8f8f8; float:left;}
# contactform textarea { width:480px; border:1px solid #e9e9e9; margin:10px 0; padding:2px; background:#f8f8f8; height:150px; float:left;}
# contactform li.buttons input { padding:3px 0; margin:0 0 0 430px; border:0; color:#FFF;}

p.response { text-align:center; color:#2c2c2c; font:bold 11px Arial, Helvetica, sans-serif; line-height:1.5em; width:auto;}
p.clr,
.clr { clear:both; padding:0; margin:0;}
li.bg,
.bg { clear:both; border-bottom:1px solid #e2e2e2; padding:10px 0 0 0; margin:0 0 10px 0; background:none; list-style:none;}

**Comment by james2doyle** [comment]
can you please explain what the issue is?
